### PR TITLE
Adding link to hson-loader for webpack

### PR DESCRIPTION
**Pull request by kentcdodds**
I just made this because hanson rocks and so does Webpack :-)

### CODE REVIEW

**Comment by kentcdodds** [comment]
ping @timjansen?

**Comment by timjansen** [comment]
Sorry, still alive. Will look at it later today (don't know Webpack).

**Comment by kentcdodds** [comment]
Here's an intro :-) https://egghead.io/lessons/javascript-intro-to-webpack

**Comment by timjansen** [comment]
Thank you :)

**Pull request merged**
