### PR TITLE
Test separation + STDIN/STDOUT support

### PR DESCRIPTION
**Pull request by hash-bang**
Big fan of the Hanson module but I'm finding that I have need for STDIN and STDOUT piping support.

The attached PR uses the standard Unix substitute character `-` to refer to I/O from these pipes accordingly. `hanson - -` would read from STDIN, transform and output to STDOUT. `-p` is also provided as a convenience switch to do this.

Additionally I separated the test kit out of one file in to multiple within `/test` and also replaced the standard NodeJS Assert library with the more flexible Chai. This allowed adding of tests for the command line.

I have *not* bumped the package version - I assume you wanted to do this yourself if you are happy with the PR.

### CODE REVIEW

**Comment by timjansen** [comment]
Awesome, thank you!

**Comment by hash-bang** [comment]
Glad I could help.

Could I trouble you for a version bump + `npm publish` so I can start rolling these changes out to various machines?

**Comment by timjansen** [comment]
Will try to do this tomorrow.

**Comment by timjansen** [comment]
just published as 1.2.0.

**Pull request merged**
